package mpslang.eu.algites.lib.common.base.type.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_AIcConceptTypeRef;
  private ConceptPresentation props_AIcParametrizedTypeRef;
  private ConceptPresentation props_AIcPrimitiveTypeRef;
  private ConceptPresentation props_AIcTypeParam;
  private ConceptPresentation props_AIcTypeParamRef;
  private ConceptPresentation props_AIcTypeRef;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.AIcConceptTypeRef:
        if (props_AIcConceptTypeRef == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x5c1d5df260c1ab35L, 0x53c7d5be0caf4cafL, "concept", "", "");
          props_AIcConceptTypeRef = cpb.create();
        }
        return props_AIcConceptTypeRef;
      case LanguageConceptSwitch.AIcParametrizedTypeRef:
        if (props_AIcParametrizedTypeRef == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("AIcParametrizedTypeRef");
          props_AIcParametrizedTypeRef = cpb.create();
        }
        return props_AIcParametrizedTypeRef;
      case LanguageConceptSwitch.AIcPrimitiveTypeRef:
        if (props_AIcPrimitiveTypeRef == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("AIcPrimitiveTypeRef");
          props_AIcPrimitiveTypeRef = cpb.create();
        }
        return props_AIcPrimitiveTypeRef;
      case LanguageConceptSwitch.AIcTypeParam:
        if (props_AIcTypeParam == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("AIcTypeParam");
          props_AIcTypeParam = cpb.create();
        }
        return props_AIcTypeParam;
      case LanguageConceptSwitch.AIcTypeParamRef:
        if (props_AIcTypeParamRef == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("AIcTypeParamRef");
          props_AIcTypeParamRef = cpb.create();
        }
        return props_AIcTypeParamRef;
      case LanguageConceptSwitch.AIcTypeRef:
        if (props_AIcTypeRef == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_AIcTypeRef = cpb.create();
        }
        return props_AIcTypeRef;
    }
    return null;
  }
}
