package mpslang.eu.algites.lib.common.base.type.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AIcConceptTypeRef = 0;
  public static final int AIcParametrizedTypeRef = 1;
  public static final int AIcPrimitiveTypeRef = 2;
  public static final int AIcTypeParam = 3;
  public static final int AIcTypeParamRef = 4;
  public static final int AIcTypeRef = 5;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL);
    builder.put(0x5c1d5df260c1ab35L, AIcConceptTypeRef);
    builder.put(0x5c1d5df260c1bfe4L, AIcParametrizedTypeRef);
    builder.put(0x5c1d5df260c1a987L, AIcPrimitiveTypeRef);
    builder.put(0x5c1d5df260c1c190L, AIcTypeParam);
    builder.put(0x5c1d5df260c1c4b3L, AIcTypeParamRef);
    builder.put(0x5c1d5df260c1a984L, AIcTypeRef);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
