package mpslang.eu.algites.lib.common.base.type.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AIcConceptTypeDescriptor = 0;
  public static final int AIcGenericTypeDescriptor = 1;
  public static final int AIcJavaTypeDescriptor = 2;
  public static final int AIcMethodDef = 3;
  public static final int AIcMethodParamDef = 4;
  public static final int AIcPrimitiveTypeDescriptor = 5;
  public static final int AIcTypeDeclaration = 6;
  public static final int AIcTypeDeclarationRefDescriptor = 7;
  public static final int AIcTypeDescriptor = 8;
  public static final int AIcTypeParamDef = 9;
  public static final int AIcTypeParamUsage = 10;
  public static final int AIcUnresolvedTypeDescriptor = 11;
  public static final int AIiMethodOwner = 12;
  public static final int AIiTypeParamOwner = 13;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL);
    builder.put(0x5c1d5df260c1ab35L, AIcConceptTypeDescriptor);
    builder.put(0x5c1d5df260c1bfe4L, AIcGenericTypeDescriptor);
    builder.put(0x7081d898a9dcb68L, AIcJavaTypeDescriptor);
    builder.put(0x14e85477227890a4L, AIcMethodDef);
    builder.put(0x14e85477227890a8L, AIcMethodParamDef);
    builder.put(0x5c1d5df260c1a987L, AIcPrimitiveTypeDescriptor);
    builder.put(0x14e85477227abbaaL, AIcTypeDeclaration);
    builder.put(0x695f40ab5b36e881L, AIcTypeDeclarationRefDescriptor);
    builder.put(0x5c1d5df260c1a984L, AIcTypeDescriptor);
    builder.put(0x5c1d5df260c1c190L, AIcTypeParamDef);
    builder.put(0x5c1d5df260c1c4b3L, AIcTypeParamUsage);
    builder.put(0x6b91f9cb881300b7L, AIcUnresolvedTypeDescriptor);
    builder.put(0x14e85477227890b5L, AIiMethodOwner);
    builder.put(0x7081d898a9047a8L, AIiTypeParamOwner);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
