package mpslang.eu.algites.lib.common.base.type.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AIcConceptTypeDescriptor = 0;
  public static final int AIcGenericTypeDescriptor = 1;
  public static final int AIcJavaTypeDescriptor = 2;
  public static final int AIcPrimitiveTypeDescriptor = 3;
  public static final int AIcTypeDescriptor = 4;
  public static final int AIcTypeParamDef = 5;
  public static final int AIcTypeParamUsage = 6;
  public static final int AIiTypeParamOwner = 7;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL);
    builder.put(0x5c1d5df260c1ab35L, AIcConceptTypeDescriptor);
    builder.put(0x5c1d5df260c1bfe4L, AIcGenericTypeDescriptor);
    builder.put(0x7081d898a9dcb68L, AIcJavaTypeDescriptor);
    builder.put(0x5c1d5df260c1a987L, AIcPrimitiveTypeDescriptor);
    builder.put(0x5c1d5df260c1a984L, AIcTypeDescriptor);
    builder.put(0x5c1d5df260c1c190L, AIcTypeParamDef);
    builder.put(0x5c1d5df260c1c4b3L, AIcTypeParamUsage);
    builder.put(0x7081d898a9047a8L, AIiTypeParamOwner);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
