package mpslang.eu.algites.lib.common.base.type.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAIcConceptTypeRef = createDescriptorForAIcConceptTypeRef();
  /*package*/ final ConceptDescriptor myConceptAIcParametrizedTypeRef = createDescriptorForAIcParametrizedTypeRef();
  /*package*/ final ConceptDescriptor myConceptAIcPrimitiveTypeRef = createDescriptorForAIcPrimitiveTypeRef();
  /*package*/ final ConceptDescriptor myConceptAIcTypeParam = createDescriptorForAIcTypeParam();
  /*package*/ final ConceptDescriptor myConceptAIcTypeParamRef = createDescriptorForAIcTypeParamRef();
  /*package*/ final ConceptDescriptor myConceptAIcTypeRef = createDescriptorForAIcTypeRef();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0x38741375005249b3L, 0x9ff14edcb48cb677L, "mpslang.eu.algites.lib.common.base");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAIcConceptTypeRef, myConceptAIcParametrizedTypeRef, myConceptAIcPrimitiveTypeRef, myConceptAIcTypeParam, myConceptAIcTypeParamRef, myConceptAIcTypeRef);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.AIcConceptTypeRef:
        return myConceptAIcConceptTypeRef;
      case LanguageConceptSwitch.AIcParametrizedTypeRef:
        return myConceptAIcParametrizedTypeRef;
      case LanguageConceptSwitch.AIcPrimitiveTypeRef:
        return myConceptAIcPrimitiveTypeRef;
      case LanguageConceptSwitch.AIcTypeParam:
        return myConceptAIcTypeParam;
      case LanguageConceptSwitch.AIcTypeParamRef:
        return myConceptAIcTypeParamRef;
      case LanguageConceptSwitch.AIcTypeRef:
        return myConceptAIcTypeRef;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAIcConceptTypeRef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mpslang.eu.algites.lib.common.base.type", "AIcConceptTypeRef", 0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x5c1d5df260c1ab35L);
    b.class_(false, false, false);
    // extends: mpslang.eu.algites.lib.common.base.type.structure.AIcTypeRef
    b.super_(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x5c1d5df260c1a984L);
    b.origin("r:7c5fb68d-7de0-4133-951b-35b2986b94da(mpslang.eu.algites.lib.common.base.type.structure)/6637564721400752949");
    b.version(3);
    b.associate("concept", 0x53c7d5be0caf4cafL).target(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, 0x6ed0e6c2f31b3f42L).optional(false).origin("6037028837746756783").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAIcParametrizedTypeRef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mpslang.eu.algites.lib.common.base.type", "AIcParametrizedTypeRef", 0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x5c1d5df260c1bfe4L);
    b.class_(false, false, false);
    // extends: mpslang.eu.algites.lib.common.base.type.structure.AIcTypeRef
    b.super_(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x5c1d5df260c1a984L);
    b.origin("r:7c5fb68d-7de0-4133-951b-35b2986b94da(mpslang.eu.algites.lib.common.base.type.structure)/6637564721400758244");
    b.version(3);
    b.aggregate("rawType", 0x53c7d5be0cb2b3ffL).target(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x5c1d5df260c1ab35L).optional(false).ordered(true).multiple(false).origin("6037028837746979839").done();
    b.aggregate("typeArguments", 0x53c7d5be0cb2b400L).target(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x5c1d5df260c1a984L).optional(true).ordered(true).multiple(true).origin("6037028837746979840").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAIcPrimitiveTypeRef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mpslang.eu.algites.lib.common.base.type", "AIcPrimitiveTypeRef", 0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x5c1d5df260c1a987L);
    b.class_(false, false, false);
    // extends: mpslang.eu.algites.lib.common.base.type.structure.AIcTypeRef
    b.super_(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x5c1d5df260c1a984L);
    b.origin("r:7c5fb68d-7de0-4133-951b-35b2986b94da(mpslang.eu.algites.lib.common.base.type.structure)/6637564721400752519");
    b.version(3);
    b.property("kind", 0x5c1d5df260c215ddL).type(MetaIdFactory.dataTypeId(0x38741375005249b3L, 0x9ff14edcb48cb677L, 0x53c7d5be0cadd323L)).origin("6637564721400780253").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAIcTypeParam() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mpslang.eu.algites.lib.common.base.type", "AIcTypeParam", 0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x5c1d5df260c1c190L);
    b.class_(false, false, false);
    b.parent(0x38741375005249b3L, 0x9ff14edcb48cb677L, 0x5c1d5df260bf9cadL);
    b.origin("r:7c5fb68d-7de0-4133-951b-35b2986b94da(mpslang.eu.algites.lib.common.base.type.structure)/6637564721400758672");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAIcTypeParamRef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mpslang.eu.algites.lib.common.base.type", "AIcTypeParamRef", 0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x5c1d5df260c1c4b3L);
    b.class_(false, false, false);
    b.parent(0x38741375005249b3L, 0x9ff14edcb48cb677L, 0x5c1d5df260bf9cadL);
    b.origin("r:7c5fb68d-7de0-4133-951b-35b2986b94da(mpslang.eu.algites.lib.common.base.type.structure)/6637564721400759475");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAIcTypeRef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mpslang.eu.algites.lib.common.base.type", "AIcTypeRef", 0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x5c1d5df260c1a984L);
    b.class_(false, true, false);
    b.parent(0x38741375005249b3L, 0x9ff14edcb48cb677L, 0x5c1d5df260bf9cadL);
    b.origin("r:7c5fb68d-7de0-4133-951b-35b2986b94da(mpslang.eu.algites.lib.common.base.type.structure)/6637564721400752516");
    b.version(3);
    return b.create();
  }
}
