package eu.algites.lib.common.util.collections.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_AIcMap;
  private ConceptPresentation props_AIiMap;
  private ConceptPresentation props_AIiMapEntry;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.AIcMap:
        if (props_AIcMap == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("AIcMap");
          props_AIcMap = cpb.create();
        }
        return props_AIcMap;
      case LanguageConceptSwitch.AIiMap:
        if (props_AIiMap == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_AIiMap = cpb.create();
        }
        return props_AIiMap;
      case LanguageConceptSwitch.AIiMapEntry:
        if (props_AIiMapEntry == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_AIiMapEntry = cpb.create();
        }
        return props_AIiMapEntry;
    }
    return null;
  }
}
