package eu.algites.lib.common.util.collections.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AIcMap = 0;
  public static final int AIiMap = 1;
  public static final int AIiMapEntry = 2;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x4fc4fa1e63a64a3aL, 0xa8aef1b9dc86385bL);
    builder.put(0x483f199f0ae75f91L, AIcMap);
    builder.put(0x483f199f0ae75f8fL, AIiMap);
    builder.put(0x168ec49948bca685L, AIiMapEntry);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
