package eu.algites.lib.common.util.collections.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAIcMap = createDescriptorForAIcMap();
  /*package*/ final ConceptDescriptor myConceptAIiMap = createDescriptorForAIiMap();
  /*package*/ final ConceptDescriptor myConceptAIiMapEntry = createDescriptorForAIiMapEntry();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAIcMap, myConceptAIiMap, myConceptAIiMapEntry);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.AIcMap:
        return myConceptAIcMap;
      case LanguageConceptSwitch.AIiMap:
        return myConceptAIiMap;
      case LanguageConceptSwitch.AIiMapEntry:
        return myConceptAIiMapEntry;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAIcMap() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("eu.algites.lib.common.util.collections", "AIcMap", 0x4fc4fa1e63a64a3aL, 0xa8aef1b9dc86385bL, 0x483f199f0ae75f91L);
    b.class_(false, false, false);
    b.parent(0x4fc4fa1e63a64a3aL, 0xa8aef1b9dc86385bL, 0x483f199f0ae75f8fL);
    b.origin("r:bc4f1f17-47f2-4f09-a80b-29d5a23ece3b(eu.algites.lib.common.util.collections.structure)/5205907865137012625");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAIiMap() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("eu.algites.lib.common.util.collections", "AIiMap", 0x4fc4fa1e63a64a3aL, 0xa8aef1b9dc86385bL, 0x483f199f0ae75f8fL);
    b.interface_();
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x11f1e14d895L);
    b.origin("r:bc4f1f17-47f2-4f09-a80b-29d5a23ece3b(eu.algites.lib.common.util.collections.structure)/5205907865137012623");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAIiMapEntry() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("eu.algites.lib.common.util.collections", "AIiMapEntry", 0x4fc4fa1e63a64a3aL, 0xa8aef1b9dc86385bL, 0x168ec49948bca685L);
    b.interface_();
    b.origin("r:bc4f1f17-47f2-4f09-a80b-29d5a23ece3b(eu.algites.lib.common.util.collections.structure)/1625452678156691077");
    b.version(3);
    return b.create();
  }
}
