package mpslang.test2.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAIcTestConcept = createDescriptorForAIcTestConcept();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAIcTestConcept);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.AIcTestConcept:
        return myConceptAIcTestConcept;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAIcTestConcept() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mpslang.test2", "AIcTestConcept", 0xe3f8888cb260492eL, 0x8b9599fa84ec7701L, 0x53c7d5be0cad12b2L);
    b.class_(false, false, false);
    b.origin("r:30577625-d822-490f-806f-2113e3bc4d8d(mpslang.test2.structure)/6037028837746610866");
    b.version(3);
    b.property("kind", 0x53c7d5be0cad12b3L).type(MetaIdFactory.dataTypeId(0x964c36cff8a84014L, 0x8c57c1bbe503ec59L, 0x53c7d5be0cad1ba4L)).origin("6037028837746610867").done();
    return b.create();
  }
}
