package mpslang.eu.algites.lib.common.util.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;

public class check_AIiIterator_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_AIiIterator_NonTypesystemRule() {
  }
  public void applyRule(final SNode aIterator, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    if (ListSequence.fromList(SLinkOperations.getChildren(aIterator, LINKS.typeParams$Hgf2)).count() != 1) {
      {
        final MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(aIterator, "iterator must define exactly one type parameter", "r:39de6ea1-7a1e-4e01-9298-dfc4df0bcd58(mpslang.eu.algites.lib.common.util.typesystem)", "506687434652495537", null, errorTarget);
      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.AIiIterator$ZI;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink typeParams$Hgf2 = MetaAdapterFactory.getContainmentLink(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x7081d898a9047a8L, 0x7081d898a91bf78L, "typeParams");
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept AIiIterator$ZI = MetaAdapterFactory.getInterfaceConcept(0x1fcc140d3b7340fbL, 0xa4493b2598f356c4L, 0x5c1d5df260c0777aL, "mpslang.eu.algites.lib.common.util.structure.AIiIterator");
  }
}
