package mpslang.eu.algites.lib.common.base.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_AIcBoolean;
  private ConceptPresentation props_AIcInteger;
  private ConceptPresentation props_AIcString;
  private ConceptPresentation props_AIiObject;
  private ConceptPresentation props_AIiPrimitiveValue;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.AIcBoolean:
        if (props_AIcBoolean == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Object represenation of boolean primitive");
          cpb.rawPresentation("BOOL");
          props_AIcBoolean = cpb.create();
        }
        return props_AIcBoolean;
      case LanguageConceptSwitch.AIcInteger:
        if (props_AIcInteger == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Object represenation of int primitive");
          cpb.rawPresentation("INT");
          props_AIcInteger = cpb.create();
        }
        return props_AIcInteger;
      case LanguageConceptSwitch.AIcString:
        if (props_AIcString == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Object represenation of string primitive");
          cpb.rawPresentation("STRING");
          props_AIcString = cpb.create();
        }
        return props_AIcString;
      case LanguageConceptSwitch.AIiObject:
        if (props_AIiObject == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_AIiObject = cpb.create();
        }
        return props_AIiObject;
      case LanguageConceptSwitch.AIiPrimitiveValue:
        if (props_AIiPrimitiveValue == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_AIiPrimitiveValue = cpb.create();
        }
        return props_AIiPrimitiveValue;
    }
    return null;
  }
}
