package mpslang.eu.algites.lib.common.base.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_AInPrimitiveKind extends EnumerationDescriptorBase {

  public EnumerationDescriptor_AInPrimitiveKind() {
    super(0x38741375005249b3L, 0x9ff14edcb48cb677L, 0x53c7d5be0cadd323L, "AInPrimitiveKind", "r:9cc8eb42-87d8-44ad-9360-c620e9171fe7(mpslang.eu.algites.lib.common.base.structure)/6037028837746660131");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_STRING_0 = new EnumerationDescriptor.MemberDescriptor("STRING", "STRING", 0x53c7d5be0cadd324L, "r:9cc8eb42-87d8-44ad-9360-c620e9171fe7(mpslang.eu.algites.lib.common.base.structure)/6037028837746660132");
  private final EnumerationDescriptor.MemberDescriptor myMember_INT_0 = new EnumerationDescriptor.MemberDescriptor("INT", "INT", 0x53c7d5be0cadd325L, "r:9cc8eb42-87d8-44ad-9360-c620e9171fe7(mpslang.eu.algites.lib.common.base.structure)/6037028837746660133");
  private final EnumerationDescriptor.MemberDescriptor myMember_BOOL_0 = new EnumerationDescriptor.MemberDescriptor("BOOL", "BOOL", 0x53c7d5be0cadd326L, "r:9cc8eb42-87d8-44ad-9360-c620e9171fe7(mpslang.eu.algites.lib.common.base.structure)/6037028837746660134");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x38741375005249b3L, 0x9ff14edcb48cb677L, 0x53c7d5be0cadd323L, 0x53c7d5be0cadd324L, 0x53c7d5be0cadd325L, 0x53c7d5be0cadd326L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_STRING_0, myMember_INT_0, myMember_BOOL_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "STRING":
        return myMember_STRING_0;
      case "INT":
        return myMember_INT_0;
      case "BOOL":
        return myMember_BOOL_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
