package mpslang.eu.algites.lib.common.base.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AIcBoolean = 0;
  public static final int AIcInteger = 1;
  public static final int AIcString = 2;
  public static final int AIiObject = 3;
  public static final int AIiPrimitiveValue = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x38741375005249b3L, 0x9ff14edcb48cb677L);
    builder.put(0x5c1d5df260bf5829L, AIcBoolean);
    builder.put(0x5c1d5df260bf1a36L, AIcInteger);
    builder.put(0x5c1d5df260be89a4L, AIcString);
    builder.put(0x5c1d5df260bf9cadL, AIiObject);
    builder.put(0x5c1d5df260be899bL, AIiPrimitiveValue);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
