package mpslang.eu.algites.lib.common.base.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAIcBoolean = createDescriptorForAIcBoolean();
  /*package*/ final ConceptDescriptor myConceptAIcInteger = createDescriptorForAIcInteger();
  /*package*/ final ConceptDescriptor myConceptAIcString = createDescriptorForAIcString();
  /*package*/ final ConceptDescriptor myConceptAIiObject = createDescriptorForAIiObject();
  /*package*/ final ConceptDescriptor myConceptAIiPrimitiveValue = createDescriptorForAIiPrimitiveValue();
  /*package*/ final EnumerationDescriptor myEnumerationAInPrimitiveKind = new EnumerationDescriptor_AInPrimitiveKind();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAIcBoolean, myConceptAIcInteger, myConceptAIcString, myConceptAIiObject, myConceptAIiPrimitiveValue);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.AIcBoolean:
        return myConceptAIcBoolean;
      case LanguageConceptSwitch.AIcInteger:
        return myConceptAIcInteger;
      case LanguageConceptSwitch.AIcString:
        return myConceptAIcString;
      case LanguageConceptSwitch.AIiObject:
        return myConceptAIiObject;
      case LanguageConceptSwitch.AIiPrimitiveValue:
        return myConceptAIiPrimitiveValue;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationAInPrimitiveKind);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAIcBoolean() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mpslang.eu.algites.lib.common.base", "AIcBoolean", 0x38741375005249b3L, 0x9ff14edcb48cb677L, 0x5c1d5df260bf5829L);
    b.class_(false, false, false);
    b.parent(0x38741375005249b3L, 0x9ff14edcb48cb677L, 0x5c1d5df260be899bL);
    b.origin("r:9cc8eb42-87d8-44ad-9360-c620e9171fe7(mpslang.eu.algites.lib.common.base.structure)/6637564721400600617");
    b.version(3);
    b.property("value", 0x5c1d5df260bf8f75L).type(PrimitiveTypeId.BOOLEAN).origin("6637564721400614773").done();
    b.alias("BOOL");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAIcInteger() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mpslang.eu.algites.lib.common.base", "AIcInteger", 0x38741375005249b3L, 0x9ff14edcb48cb677L, 0x5c1d5df260bf1a36L);
    b.class_(false, false, false);
    b.parent(0x38741375005249b3L, 0x9ff14edcb48cb677L, 0x5c1d5df260be899bL);
    b.origin("r:9cc8eb42-87d8-44ad-9360-c620e9171fe7(mpslang.eu.algites.lib.common.base.structure)/6637564721400584758");
    b.version(3);
    b.property("value", 0x5c1d5df260bf8f74L).type(PrimitiveTypeId.INTEGER).origin("6637564721400614772").done();
    b.alias("INT");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAIcString() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mpslang.eu.algites.lib.common.base", "AIcString", 0x38741375005249b3L, 0x9ff14edcb48cb677L, 0x5c1d5df260be89a4L);
    b.class_(false, false, false);
    b.parent(0x38741375005249b3L, 0x9ff14edcb48cb677L, 0x5c1d5df260be899bL);
    b.origin("r:9cc8eb42-87d8-44ad-9360-c620e9171fe7(mpslang.eu.algites.lib.common.base.structure)/6637564721400547748");
    b.version(3);
    b.property("value", 0x5c1d5df260bf7c3bL).type(PrimitiveTypeId.STRING).origin("6637564721400609851").done();
    b.alias("STRING");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAIiObject() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mpslang.eu.algites.lib.common.base", "AIiObject", 0x38741375005249b3L, 0x9ff14edcb48cb677L, 0x5c1d5df260bf9cadL);
    b.interface_();
    b.origin("r:9cc8eb42-87d8-44ad-9360-c620e9171fe7(mpslang.eu.algites.lib.common.base.structure)/6637564721400618157");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAIiPrimitiveValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mpslang.eu.algites.lib.common.base", "AIiPrimitiveValue", 0x38741375005249b3L, 0x9ff14edcb48cb677L, 0x5c1d5df260be899bL);
    b.interface_();
    b.parent(0x38741375005249b3L, 0x9ff14edcb48cb677L, 0x5c1d5df260bf9cadL);
    b.origin("r:9cc8eb42-87d8-44ad-9360-c620e9171fe7(mpslang.eu.algites.lib.common.base.structure)/6637564721400547739");
    b.version(3);
    return b.create();
  }
}
