package mpslang.eu.algites.lib.common.base.type.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;

public class check_AIcParametrizedTypeRef_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_AIcParametrizedTypeRef_NonTypesystemRule() {
  }
  public void applyRule(final SNode aParametrizedTypeRef, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    if (SLinkOperations.getTarget(aParametrizedTypeRef, LINKS.rawType$p1DC) == null) {
      {
        final MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(aParametrizedTypeRef, "Parametrized type ref needs to have defined its raw type", "r:dd7da66f-6c7b-4348-ba60-c1b8a5d64ae5(mpslang.eu.algites.lib.common.base.type.typesystem)", "6037028837746995156", null, errorTarget);
      }
    }
    if (ListSequence.fromList(SLinkOperations.getChildren(aParametrizedTypeRef, LINKS.typeArguments$p6NY)).count() == 0) {
      {
        final MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(aParametrizedTypeRef, "Parametrized type ref needs at least one generic parameter", "r:dd7da66f-6c7b-4348-ba60-c1b8a5d64ae5(mpslang.eu.algites.lib.common.base.type.typesystem)", "6037028837747029797", null, errorTarget);
      }
    }
    String locErrorMessage = "";
    for (int i = 0; i < ListSequence.fromList(SLinkOperations.getChildren(aParametrizedTypeRef, LINKS.typeArguments$p6NY)).count(); i++) {
      if (ListSequence.fromList(SLinkOperations.getChildren(aParametrizedTypeRef, LINKS.typeArguments$p6NY)).getElement(i) == null) {
        if (!(locErrorMessage.equals(""))) {
          locErrorMessage = locErrorMessage + ", ";
        }
        locErrorMessage = locErrorMessage + i;
      }
    }
    if (!(locErrorMessage.equals(""))) {
      {
        final MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(aParametrizedTypeRef, "Following typeArgument array positions are undefined:" + locErrorMessage, "r:dd7da66f-6c7b-4348-ba60-c1b8a5d64ae5(mpslang.eu.algites.lib.common.base.type.typesystem)", "6037028837747087901", null, errorTarget);
      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.AIcParametrizedTypeRef$mM;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink rawType$p1DC = MetaAdapterFactory.getContainmentLink(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x5c1d5df260c1bfe4L, 0x53c7d5be0cb2b3ffL, "rawType");
    /*package*/ static final SContainmentLink typeArguments$p6NY = MetaAdapterFactory.getContainmentLink(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x5c1d5df260c1bfe4L, 0x53c7d5be0cb2b400L, "typeArguments");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept AIcParametrizedTypeRef$mM = MetaAdapterFactory.getConcept(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x5c1d5df260c1bfe4L, "mpslang.eu.algites.lib.common.base.type.structure.AIcParametrizedTypeRef");
  }
}
