package mpslang.eu.algites.lib.common.base.type.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;

public class check_AIcJavaTypeDescriptor_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_AIcJavaTypeDescriptor_NonTypesystemRule() {
  }
  public void applyRule(final SNode aJavaTypeDescriptor, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    if (SPropertyOperations.getString(aJavaTypeDescriptor, PROPS.qualifiedJavaTypeName$QJrQ) == null || SPropertyOperations.getString(aJavaTypeDescriptor, PROPS.qualifiedJavaTypeName$QJrQ).trim().length() == 0) {
      {
        final MessageTarget errorTarget = new NodeMessageTarget();
        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(aJavaTypeDescriptor, "qualifiedJavaTypeName must be defined", "r:dd7da66f-6c7b-4348-ba60-c1b8a5d64ae5(mpslang.eu.algites.lib.common.base.type.typesystem)", "506687434653223893", null, errorTarget);
      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.AIcJavaTypeDescriptor$bY;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class PROPS {
    /*package*/ static final SProperty qualifiedJavaTypeName$QJrQ = MetaAdapterFactory.getProperty(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x7081d898a9dcb68L, 0x7081d898a9dcb69L, "qualifiedJavaTypeName");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept AIcJavaTypeDescriptor$bY = MetaAdapterFactory.getConcept(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x7081d898a9dcb68L, "mpslang.eu.algites.lib.common.base.type.structure.AIcJavaTypeDescriptor");
  }
}
