package mpslang.eu.algites.lib.common.base.type.utils;

/*Generated by MPS */

import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;
import java.util.ArrayList;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import mpslang.eu.algites.lib.common.base.behavior.AIiObject__BehaviorDescriptor;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import org.jetbrains.mps.openapi.language.SConcept;

public class AIsTypeParamUtils {
  /**
   * Collects visible type parameters for the given context node by walking up
   * the ancestor chain and aggregating type parameters from all {@code ATiTypeParamOwner} ancestors.
   * 
   * The nearest owner contributes first, then outer owners.
   * 
   * @param aContextNode context node inside a scope
   * @return visible type parameter definitions
   */
  public static List<SNode> collectVisibleTypeParamDefs(SNode aContextNode) {
    List<SNode> locResult = new ArrayList<SNode>();
    SNode locCurrentNode = aContextNode;
    while ((locCurrentNode != null)) {
      if (SNodeOperations.isInstanceOf(locCurrentNode, CONCEPTS.AIiTypeParamOwner$fM)) {
        SNode locOwner = ((SNode) locCurrentNode);
        ListSequence.fromList(locResult).addSequence(ListSequence.fromList(SLinkOperations.getChildren(locOwner, LINKS.typeParams$Hgf2)));
      }
      locCurrentNode = SNodeOperations.getParent(locCurrentNode);
    }
    return locResult;
  }

  /**
   * Returns the parameters declared directly on given owner
   * 
   * 
   * @param aOwner type parameter owner
   * @return declared parameter definitions
   */
  public static List<SNode> collectDeclaredTypeParamDefs(SNode aOwner) {
    List<SNode> locResult = new ArrayList<SNode>();
    if (aOwner != null) {
      ListSequence.fromList(locResult).addSequence(ListSequence.fromList(SLinkOperations.getChildren(aOwner, LINKS.typeParams$Hgf2)));
    }
    return locResult;
  }


  /**
   * Performs the rendering of the parametrized type
   * 
   * 
   * @param aRawTypeText rendering of the given raw type
   * @param aDescriptors descriptors of the parameters of the raw type
   * @return the rendered test of the given type
   */
  public static String renderParametrizedType(String aRawTypeText, List<SNode> aDescriptors) {
    if (aDescriptors == null || ListSequence.fromList(aDescriptors).isEmpty()) {
      return aRawTypeText + "<???>";
    }
    String locArgsText = "";
    boolean locIsFirst = true;

    for (SNode locArg : aDescriptors) {
      String locArgText = ((locArg == null) ? "?" : AIiObject__BehaviorDescriptor.render_id5Ktnv9wJTN1.invoke(locArg));
      if (locArgText == null) {
        locArgText = "undefined-render-error-of:" + SNodeOperations.getConcept(locArg);
      }
      if (locIsFirst) {
        locArgsText = locArgText;
        locIsFirst = false;
      } else {
        locArgsText = locArgsText + ", " + locArgText;
      }
    }
    return aRawTypeText + "<" + locArgsText + ">";
  }


  /**
   * Performs the wrapping of the passed type descriptor into the generic type as a base type
   * 
   * 
   * @param aTypeToWrap concept of the type which should be wrapped as a base type into the new generic type,
   *                    which will automatically replace this passed concept on all places
   *                    
   * @param aEditorContext editor context in which the replacement happens
   */
  public static void editorWrapIntoGeneric(SNode aTypeToWrap, EditorContext aEditorContext) {
    /*
      Wrap the current type descriptor into AIcGenericTypeDescriptor when user presses '<'.

    */

    SNode locCurrentDescriptor = aTypeToWrap;
    SNode locParentNode = SNodeOperations.getParent(locCurrentDescriptor);
    /*
      If we are already editing the baseType of an existing generic descriptor, do not nest generics.
      Just ensure there is at least one type argument and move the caret there.

    */

    if (locParentNode != null && SNodeOperations.isInstanceOf(locParentNode, CONCEPTS.AIcGenericTypeDescriptor$mM)) {
      SNode locExistingGeneric = ((SNode) locParentNode);

      if (locCurrentDescriptor == SLinkOperations.getTarget(locExistingGeneric, LINKS.baseType$p1DC)) {
        if (ListSequence.fromList(SLinkOperations.getChildren(locExistingGeneric, LINKS.typeArguments$p6NY)).isEmpty()) {
          SNode locNewDescriptor = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x6b91f9cb881300b7L, "mpslang.eu.algites.lib.common.base.type.structure.AIcUnresolvedTypeDescriptor"));
          ListSequence.fromList(SLinkOperations.getChildren(locExistingGeneric, LINKS.typeArguments$p6NY)).addElement(locNewDescriptor);
        }
        return;
      }

    }
    SNode locNewGeneric = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x5c1d5df260c1bfe4L, "mpslang.eu.algites.lib.common.base.type.structure.AIcGenericTypeDescriptor"));
    /*
      Replace current node in the AST with the new generic wrapper:

    */

    SNodeOperations.replaceWithAnother(locCurrentDescriptor, locNewGeneric);

    /*
      Move the former node under baseType of the wrapper:

    */

    SLinkOperations.setTarget(locNewGeneric, LINKS.baseType$p1DC, locCurrentDescriptor);
    /*
      Create the first undefined generic element:

    */

    SNode locNewDescriptor = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x6b91f9cb881300b7L, "mpslang.eu.algites.lib.common.base.type.structure.AIcUnresolvedTypeDescriptor"));
    ListSequence.fromList(SLinkOperations.getChildren(locNewGeneric, LINKS.typeArguments$p6NY)).addElement(locNewDescriptor);
    /*
      Focus the new argument to perform the replacement:

    */

    if (aEditorContext != null) {
      aEditorContext.select(locNewDescriptor);
    }
    return;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink typeParams$Hgf2 = MetaAdapterFactory.getContainmentLink(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x7081d898a9047a8L, 0x7081d898a91bf78L, "typeParams");
    /*package*/ static final SContainmentLink baseType$p1DC = MetaAdapterFactory.getContainmentLink(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x5c1d5df260c1bfe4L, 0x53c7d5be0cb2b3ffL, "baseType");
    /*package*/ static final SContainmentLink typeArguments$p6NY = MetaAdapterFactory.getContainmentLink(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x5c1d5df260c1bfe4L, 0x53c7d5be0cb2b400L, "typeArguments");
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept AIiTypeParamOwner$fM = MetaAdapterFactory.getInterfaceConcept(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x7081d898a9047a8L, "mpslang.eu.algites.lib.common.base.type.structure.AIiTypeParamOwner");
    /*package*/ static final SConcept AIcGenericTypeDescriptor$mM = MetaAdapterFactory.getConcept(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x5c1d5df260c1bfe4L, "mpslang.eu.algites.lib.common.base.type.structure.AIcGenericTypeDescriptor");
  }
}
