package mpslang.eu.algites.lib.common.base.type.utils;

/*Generated by MPS */

import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;
import java.util.ArrayList;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import mpslang.eu.algites.lib.common.base.behavior.AIiObject__BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;

public class AIsTypeParamUtils {
  /**
   * Collects visible type parameters for the given context node by walking up
   * the ancestor chain and aggregating type parameters from all {@code ATiTypeParamOwner} ancestors.
   * 
   * The nearest owner contributes first, then outer owners.
   * 
   * @param aContextNode context node inside a scope
   * @return visible type parameter definitions
   */
  public static List<SNode> collectVisibleTypeParamDefs(SNode aContextNode) {
    List<SNode> locResult = new ArrayList<SNode>();
    SNode locCurrentNode = aContextNode;
    while ((locCurrentNode != null)) {
      if (SNodeOperations.isInstanceOf(locCurrentNode, CONCEPTS.AIiTypeParamOwner$fM)) {
        SNode locOwner = ((SNode) locCurrentNode);
        ListSequence.fromList(locResult).addSequence(ListSequence.fromList(SLinkOperations.getChildren(locOwner, LINKS.typeParams$Hgf2)));
      }
      locCurrentNode = SNodeOperations.getParent(locCurrentNode);
    }
    return locResult;
  }

  /**
   * Returns the parameters declared directly on given owner
   * 
   * 
   * @param aOwner type parameter owner
   * @return declared parameter definitions
   */
  public static List<SNode> collectDeclaredTypeParamDefs(SNode aOwner) {
    List<SNode> locResult = new ArrayList<SNode>();
    if (aOwner != null) {
      ListSequence.fromList(locResult).addSequence(ListSequence.fromList(SLinkOperations.getChildren(aOwner, LINKS.typeParams$Hgf2)));
    }
    return locResult;
  }


  /**
   * Performs the rendering of the parametrized type
   * 
   * 
   * @param aRawTypeText rendering of the given raw type
   * @param aDescriptors descriptors of the parameters of the raw type
   * @return the rendered test of the given type
   */
  public static String renderParametrizedType(String aRawTypeText, List<SNode> aDescriptors) {
    if (aDescriptors == null || ListSequence.fromList(aDescriptors).isEmpty()) {
      return aRawTypeText + "<???>";
    }
    String locArgsText = "";
    boolean locIsFirst = true;

    for (SNode locArg : aDescriptors) {
      String locArgText = ((locArg == null) ? "?" : AIiObject__BehaviorDescriptor.render_id5Ktnv9wJTN1.invoke(locArg));
      if (locArgText == null) {
        locArgText = "undefined-render-error-of:" + SNodeOperations.getConcept(locArg);
      }
      if (locIsFirst) {
        locArgsText = locArgText;
        locIsFirst = false;
      } else {
        locArgsText = locArgsText + ", " + locArgText;
      }
    }
    return aRawTypeText + "<" + locArgsText + ">";
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink typeParams$Hgf2 = MetaAdapterFactory.getContainmentLink(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x7081d898a9047a8L, 0x7081d898a91bf78L, "typeParams");
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept AIiTypeParamOwner$fM = MetaAdapterFactory.getInterfaceConcept(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x7081d898a9047a8L, "mpslang.eu.algites.lib.common.base.type.structure.AIiTypeParamOwner");
  }
}
