package mpslang.eu.algites.lib.common.base.type.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myAIcJavaTypeDescriptor__BehaviorDescriptor = new AIcJavaTypeDescriptor__BehaviorDescriptor();
  private final BHDescriptor myAIcPrimitiveTypeDescriptor__BehaviorDescriptor = new AIcPrimitiveTypeDescriptor__BehaviorDescriptor();
  private final BHDescriptor myAIcConceptTypeDescriptor__BehaviorDescriptor = new AIcConceptTypeDescriptor__BehaviorDescriptor();
  private final BHDescriptor myAIcGenericTypeDescriptor__BehaviorDescriptor = new AIcGenericTypeDescriptor__BehaviorDescriptor();
  private final BHDescriptor myAIcTypeParamDef__BehaviorDescriptor = new AIcTypeParamDef__BehaviorDescriptor();
  private final BHDescriptor myAIcTypeParamUsage__BehaviorDescriptor = new AIcTypeParamUsage__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return myAIcConceptTypeDescriptor__BehaviorDescriptor;
      case 1:
        return myAIcGenericTypeDescriptor__BehaviorDescriptor;
      case 2:
        return myAIcJavaTypeDescriptor__BehaviorDescriptor;
      case 3:
        return myAIcPrimitiveTypeDescriptor__BehaviorDescriptor;
      case 4:
        return myAIcTypeParamDef__BehaviorDescriptor;
      case 5:
        return myAIcTypeParamUsage__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x5c1d5df260c1ab35L), MetaIdFactory.conceptId(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x5c1d5df260c1bfe4L), MetaIdFactory.conceptId(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x7081d898a9dcb68L), MetaIdFactory.conceptId(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x5c1d5df260c1a987L), MetaIdFactory.conceptId(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x5c1d5df260c1c190L), MetaIdFactory.conceptId(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x5c1d5df260c1c4b3L)).seal();
}
