package mpslang.eu.algites.lib.common.base.type.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseScopeProvider;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import mpslang.eu.algites.lib.common.base.type.utils.AIsTypeParamUtils;
import jetbrains.mps.scope.ListScope;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class AIcTypeParamUsage_Constraints extends BaseConstraintsDescriptor {
  public AIcTypeParamUsage_Constraints() {
    super(CONCEPTS.AIcTypeParamUsage$5j);
  }

  @Override
  protected Map<SReferenceLink, ReferenceConstraintsDescriptor> getSpecifiedReferences() {
    BaseReferenceConstraintsDescriptor d0 = new BaseReferenceConstraintsDescriptor(LINKS.typeParam$1Cc9, this, true, false) {
      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseScopeProvider() {
          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return new SNodePointer("r:ffb122de-718f-4f43-9383-dc08c4acaf58(mpslang.eu.algites.lib.common.base.type.constraints)", "506687434651910580");
          }
          @Override
          public Scope createScope(final ReferenceConstraintsContext _context) {
            SNode locContextNode = _context.getContextNode();
            if (locContextNode == null) {
              locContextNode = _context.getReferenceNode();
            }
            List<SNode> locCandidates = AIsTypeParamUtils.collectVisibleTypeParamDefs(locContextNode);
            return new ListScope(locCandidates) {
              @Override
              public String getName(SNode aChild) {
                if (aChild == null) {
                  return "";
                }
                SNode locDef = ((SNode) aChild);
                if (SPropertyOperations.getString(locDef, PROPS.identifier$4G1F) == null) {
                  return "";
                }
                return SPropertyOperations.getString(locDef, PROPS.identifier$4G1F).trim();
              }
            };
          }
        };
      }
    };
    Map<SReferenceLink, ReferenceConstraintsDescriptor> references = new HashMap<SReferenceLink, ReferenceConstraintsDescriptor>();
    references.put(d0.getReference(), d0);
    return references;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept AIcTypeParamUsage$5j = MetaAdapterFactory.getConcept(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x5c1d5df260c1c4b3L, "mpslang.eu.algites.lib.common.base.type.structure.AIcTypeParamUsage");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink typeParam$1Cc9 = MetaAdapterFactory.getReferenceLink(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x5c1d5df260c1c4b3L, 0x7081d898a8f8bdfL, "typeParam");
  }

  private static final class PROPS {
    /*package*/ static final SProperty identifier$4G1F = MetaAdapterFactory.getProperty(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x5c1d5df260c1c190L, 0x7081d898a8711d4L, "identifier");
  }
}
