package mpslang.eu.algites.lib.common.base.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myAIiPrimitiveValue__BehaviorDescriptor = new AIiPrimitiveValue__BehaviorDescriptor();
  private final BHDescriptor myAIcString__BehaviorDescriptor = new AIcString__BehaviorDescriptor();
  private final BHDescriptor myAIcInteger__BehaviorDescriptor = new AIcInteger__BehaviorDescriptor();
  private final BHDescriptor myAIcBoolean__BehaviorDescriptor = new AIcBoolean__BehaviorDescriptor();
  private final BHDescriptor myAIiObject__BehaviorDescriptor = new AIiObject__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return myAIcBoolean__BehaviorDescriptor;
      case 1:
        return myAIcInteger__BehaviorDescriptor;
      case 2:
        return myAIcString__BehaviorDescriptor;
      case 3:
        return myAIiObject__BehaviorDescriptor;
      case 4:
        return myAIiPrimitiveValue__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x38741375005249b3L, 0x9ff14edcb48cb677L, 0x5c1d5df260bf5829L), MetaIdFactory.conceptId(0x38741375005249b3L, 0x9ff14edcb48cb677L, 0x5c1d5df260bf1a36L), MetaIdFactory.conceptId(0x38741375005249b3L, 0x9ff14edcb48cb677L, 0x5c1d5df260be89a4L), MetaIdFactory.conceptId(0x38741375005249b3L, 0x9ff14edcb48cb677L, 0x5c1d5df260bf9cadL), MetaIdFactory.conceptId(0x38741375005249b3L, 0x9ff14edcb48cb677L, 0x5c1d5df260be899bL)).seal();
}
