package mpslang.eu.algites.lib.common.util.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAIiIterator = createDescriptorForAIiIterator();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, "mpslang.eu.algites.lib.common.base.type");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAIiIterator);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.AIiIterator:
        return myConceptAIiIterator;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAIiIterator() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mpslang.eu.algites.lib.common.util", "AIiIterator", 0x1fcc140d3b7340fbL, 0xa4493b2598f356c4L, 0x5c1d5df260c0777aL);
    b.interface_();
    b.parent(0x70f453cd5d6c40a7L, 0xba138d10610c56bcL, 0x7081d898a9047a8L);
    b.origin("r:3630e077-1428-44b0-a6dc-f74df5328867(mpslang.eu.algites.lib.common.util.structure)/6637564721400674170");
    b.version(3);
    return b.create();
  }
}
