artifactId=pub.lib.Mps_common.base
contentsModel=
description=
gradleProjectPath=
groupId=eu.algites.lib.mps.common
kind=
localArtifactId=common.base
name=
path=
type=mps
version.lane=1
version.qualifierKind=SNAPSHOT
version.qualifierLabel=SNAPSHOT
version.resolvedValue=1.0-SNAPSHOT
version.revision=0
