package mpslang.eu.algites.lib.common.base.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class AIiPrimitiveValue_Constraints extends BaseConstraintsDescriptor {
  public AIiPrimitiveValue_Constraints() {
    super(CONCEPTS.AIiPrimitiveValue$aN);
  }

  private static final class CONCEPTS {
    /*package*/ static final SInterfaceConcept AIiPrimitiveValue$aN = MetaAdapterFactory.getInterfaceConcept(0x38741375005249b3L, 0x9ff14edcb48cb677L, 0x5c1d5df260be899bL, "mpslang.eu.algites.lib.common.base.structure.AIiPrimitiveValue");
  }
}
