package mpslang.eu.algites.lib.common.datatype.i18n.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_AIcLanguageCatalog;
  private ConceptPresentation props_AIcLanguageDef;
  private ConceptPresentation props_AIcStringLocalization;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.AIcLanguageCatalog:
        if (props_AIcLanguageCatalog == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("languages");
          props_AIcLanguageCatalog = cpb.create();
        }
        return props_AIcLanguageCatalog;
      case LanguageConceptSwitch.AIcLanguageDef:
        if (props_AIcLanguageDef == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("language");
          props_AIcLanguageDef = cpb.create();
        }
        return props_AIcLanguageDef;
      case LanguageConceptSwitch.AIcStringLocalization:
        if (props_AIcStringLocalization == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("stringloc_f");
          props_AIcStringLocalization = cpb.create();
        }
        return props_AIcStringLocalization;
    }
    return null;
  }
}
