package mpslang.eu.algites.lib.common.datatype.i18n.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AIcLanguageCatalog = 0;
  public static final int AIcLanguageDef = 1;
  public static final int AIcStringLocalization = 2;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x85764b6357e04917L, 0xa9f5e938a750bf8bL);
    builder.put(0x665c3edc4d0fb9baL, AIcLanguageCatalog);
    builder.put(0x665c3edc4d0fb536L, AIcLanguageDef);
    builder.put(0x665c3edc4d0fc330L, AIcStringLocalization);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
