package mpslang.eu.algites.lib.common.datatype.i18n.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAIcLanguageCatalog = createDescriptorForAIcLanguageCatalog();
  /*package*/ final ConceptDescriptor myConceptAIcLanguageDef = createDescriptorForAIcLanguageDef();
  /*package*/ final ConceptDescriptor myConceptAIcStringLocalization = createDescriptorForAIcStringLocalization();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAIcLanguageCatalog, myConceptAIcLanguageDef, myConceptAIcStringLocalization);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.AIcLanguageCatalog:
        return myConceptAIcLanguageCatalog;
      case LanguageConceptSwitch.AIcLanguageDef:
        return myConceptAIcLanguageDef;
      case LanguageConceptSwitch.AIcStringLocalization:
        return myConceptAIcStringLocalization;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAIcLanguageCatalog() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mpslang.eu.algites.lib.common.datatype.i18n", "AIcLanguageCatalog", 0x85764b6357e04917L, 0xa9f5e938a750bf8bL, 0x665c3edc4d0fb9baL);
    b.class_(false, false, true);
    b.origin("r:936c57c6-2ecf-461a-93df-f432e7590aca(mpslang.eu.algites.lib.common.datatype.i18n.structure)/7375839405632633274");
    b.version(3);
    b.aggregate("languages", 0x665c3edc4d0fb9bdL).target(0x85764b6357e04917L, 0xa9f5e938a750bf8bL, 0x665c3edc4d0fb536L).optional(false).ordered(true).multiple(true).origin("7375839405632633277").done();
    b.alias("languages");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAIcLanguageDef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mpslang.eu.algites.lib.common.datatype.i18n", "AIcLanguageDef", 0x85764b6357e04917L, 0xa9f5e938a750bf8bL, 0x665c3edc4d0fb536L);
    b.class_(false, false, false);
    b.origin("r:936c57c6-2ecf-461a-93df-f432e7590aca(mpslang.eu.algites.lib.common.datatype.i18n.structure)/7375839405632632118");
    b.version(3);
    b.property("codeBiographic", 0x665c3edc4d0fb537L).type(PrimitiveTypeId.STRING).origin("7375839405632632119").done();
    b.property("codeTerminologic", 0x665c3edc4d0fb538L).type(PrimitiveTypeId.STRING).origin("7375839405632632120").done();
    b.property("codeSimplified", 0x665c3edc4d0fb539L).type(PrimitiveTypeId.STRING).origin("7375839405632632121").done();
    b.property("defaultName", 0x665c3edc4d0fb53aL).type(PrimitiveTypeId.STRING).origin("7375839405632632122").done();
    b.aggregate("localizedNames", 0x665c3edc4d0fb53bL).target(0x85764b6357e04917L, 0xa9f5e938a750bf8bL, 0x665c3edc4d0fc330L).optional(false).ordered(true).multiple(true).origin("7375839405632632123").done();
    b.alias("language");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAIcStringLocalization() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("mpslang.eu.algites.lib.common.datatype.i18n", "AIcStringLocalization", 0x85764b6357e04917L, 0xa9f5e938a750bf8bL, 0x665c3edc4d0fc330L);
    b.class_(false, false, false);
    b.origin("r:936c57c6-2ecf-461a-93df-f432e7590aca(mpslang.eu.algites.lib.common.datatype.i18n.structure)/7375839405632635696");
    b.version(3);
    b.property("text", 0x665c3edc4d0fc331L).type(PrimitiveTypeId.STRING).origin("7375839405632635697").done();
    b.aggregate("language", 0x665c3edc4d0fc332L).target(0x85764b6357e04917L, 0xa9f5e938a750bf8bL, 0x665c3edc4d0fb536L).optional(false).ordered(true).multiple(false).origin("7375839405632635698").done();
    b.alias("stringloc_f");
    return b.create();
  }
}
