package mpslang.test1.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_AInStructureMyTestEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_AInStructureMyTestEnum() {
    super(0x964c36cff8a84014L, 0x8c57c1bbe503ec59L, 0x53c7d5be0cad1ba4L, "AInStructureMyTestEnum", "r:c94dbecc-0f90-4bfd-9d48-05f203442439(mpslang.test1.structure)/6037028837746613156");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_ITEM1_0 = new EnumerationDescriptor.MemberDescriptor("ITEM1", "ITEM1", 0x53c7d5be0cad1ba5L, "r:c94dbecc-0f90-4bfd-9d48-05f203442439(mpslang.test1.structure)/6037028837746613157");
  private final EnumerationDescriptor.MemberDescriptor myMember_ITEM2_0 = new EnumerationDescriptor.MemberDescriptor("ITEM2", "ITEM2", 0x53c7d5be0cad1ba6L, "r:c94dbecc-0f90-4bfd-9d48-05f203442439(mpslang.test1.structure)/6037028837746613158");
  private final EnumerationDescriptor.MemberDescriptor myMember_ITEM3_0 = new EnumerationDescriptor.MemberDescriptor("ITEM3", "ITEM3", 0x53c7d5be0cad1ba7L, "r:c94dbecc-0f90-4bfd-9d48-05f203442439(mpslang.test1.structure)/6037028837746613159");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x964c36cff8a84014L, 0x8c57c1bbe503ec59L, 0x53c7d5be0cad1ba4L, 0x53c7d5be0cad1ba5L, 0x53c7d5be0cad1ba6L, 0x53c7d5be0cad1ba7L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_ITEM1_0, myMember_ITEM2_0, myMember_ITEM3_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "ITEM1":
        return myMember_ITEM1_0;
      case "ITEM2":
        return myMember_ITEM2_0;
      case "ITEM3":
        return myMember_ITEM3_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
